apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: pkw0301/intellipaat:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: "webapp-myapp-svc"             #name of service
spec:                               #service and pod connection properties
  selector:                         #the selector value of service should match with pod "Label"
    app: myapp                    #key and value
  ports:
    - protocol: "TCP"                   #TCP, UDP, TLS
      port: 80
      targetPort: 80
  type: NodePort 
